-- Add migration script here

CREATE TABLE IF NOT EXISTS user_management.profile_pictures (
    id bigint GENERATED BY DEFAULT AS IDENTITY (MINVALUE 0 START WITH 0) PRIMARY KEY,
    username varchar(32) NOT NULL REFERENCES user_management.users (username) ON DELETE CASCADE
);

CREATE UNIQUE INDEX ON user_management.profile_pictures (username);
