-- Add migration script here

CREATE SCHEMA IF NOT EXISTS user_management;

CREATE TYPE hash_scheme AS ENUM ('argon2_v01');

CREATE TABLE IF NOT EXISTS user_management.users (
    -- id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    first_name varchar(32) NOT NULL,
    last_name varchar(32) NOT NULL,
    email varchar(255) NOT NULL UNIQUE,
    username varchar(32) NOT NULL UNIQUE,
    pwd_hash varchar(128) NOT NULL,
    pwd_salt varchar(32) NOT NULL,
    -- jwt_salt varchar(32) NOT NULL,
    hash_scheme hash_scheme NOT NULL,
    created_at timestamp NOT NULL DEFAULT now(),
    deactivated_at timestamp DEFAULT NULL
);
