-- Add migration script here

CREATE TABLE IF NOT EXISTS post_management.likes (
    id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    post_id bigint NOT NULL REFERENCES post_management.posts (id) ON DELETE CASCADE,
    username varchar(32) NOT NULL REFERENCES user_management.users (username) ON DELETE CASCADE
);

CREATE UNIQUE INDEX likes_index ON post_management.likes (post_id);

CREATE TABLE IF NOT EXISTS post_management.comments (
    id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    post_id bigint NOT NULL REFERENCES post_management.posts (id) ON DELETE CASCADE,
    username varchar(32) NOT NULL REFERENCES user_management.users (username) ON DELETE CASCADE,
    comment varchar(1000) NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    deactivated_at timestamp with time zone DEFAULT NULL
);

CREATE UNIQUE INDEX comments_index ON post_management.comments (post_id);
