CREATE TABLE IF NOT EXISTS post_management.comments (
    id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    post_id bigint NOT NULL REFERENCES post_management.posts (id) ON DELETE CASCADE,
    username varchar(32) NOT NULL REFERENCES user_management.users (username) ON DELETE CASCADE ON UPDATE CASCADE,
    comment varchar(500)
);

CREATE INDEX ON post_management.comments (post_id);

CREATE TABLE IF NOT EXISTS user_management.following (
    id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    follower varchar(32) NOT NULL REFERENCES user_management.users (username) ON DELETE CASCADE ON UPDATE CASCADE,
    following varchar(32) NOT NULL REFERENCES user_management.users (username) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX ON user_management.following (follower);
